name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }}) 
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.7"]

    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: update-m32

      - name: Conda info
        run: conda info

      - name: Conda list
        run: conda list

      - name: Python version
        run: python --version
